### ISSUE TITLE
Check winAscent values

### ISSUE THREAD

**Issue by RosaWagner** [jenskutilek/homecomputer-fonts#7] opened 2021-08-05 12:11 UTC
Fontbakery is reporting winAscent is inferior to Y-max for workbench

**Comment by jenskutilek** [comment] 2023-06-22 07:19
That's intentional in this case, because when set without leading, the pixels (blobs) of consecutive lines should overlap when the SCAN axis is set to large values, as they do inside each line.

![Bildschirmfoto 2023-06-22 um 09 18 23](https://github.com/jenskutilek/homecomputer-fonts/assets/3185950/4eb6b29c-aec3-44f7-90db-d4458b8c4492)

**Comment by vv-monsalve** [comment] 2023-07-25 22:38
There are three FB Fails reported for the fonts.

**Sixtyfour**
<details><summary>🔥 <b>FAIL:</b> Check font follows the Google Fonts vertical metric schema (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vertical_metrics">com.google.fonts/check/vertical_metrics</a>)</summary><div>

>
>This check generally enforces Google Fonts’ vertical metrics specifications. In particular: * lineGap must be 0 * Sum of hhea ascender + abs(descender) + linegap must be between 120% and 200% of UPM * Warning if sum is over 150% of UPM
>
>The threshold levels 150% (WARN) and 200% (FAIL) are somewhat arbitrarily chosen and may hint at a glaring mistake in the metrics calculations or UPM settings.
>
>Our documentation includes further information: https://github.com/googlefonts/gf-docs/tree/main/VerticalMetrics
>
* 🔥 **FAIL** The sum of hhea.ascender + abs(hhea.descender) + hhea.lineGap is 1024 when it should be at least 1228 [code: bad-hhea-range]
</div></details>

**Workbench**
<details><summary>🔥 <b>FAIL:</b> Check font follows the Google Fonts vertical metric schema (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vertical_metrics">com.google.fonts/check/vertical_metrics</a>)</summary><div>

>
>This check generally enforces Google Fonts’ vertical metrics specifications. In particular: * lineGap must be 0 * Sum of hhea ascender + abs(descender) + linegap must be between 120% and 200% of UPM * Warning if sum is over 150% of UPM
>
>The threshold levels 150% (WARN) and 200% (FAIL) are somewhat arbitrarily chosen and may hint at a glaring mistake in the metrics calculations or UPM settings.
>
>Our documentation includes further information: https://github.com/googlefonts/gf-docs/tree/main/VerticalMetrics
>
* 🔥 **FAIL** The sum of hhea.ascender + abs(hhea.descender) + hhea.lineGap is 1024 when it should be at least 1228 [code: bad-hhea-range]
</div></details><details><summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent">com.google.fonts/check/family/win_ascent_and_descent</a>)</summary><div>

>
>A font's winAscent and winDescent values should be greater than or equal to the head table's yMax, abs(yMin) values. If they are less than these values, clipping can occur on Windows platforms (https://github.com/RedHatBrand/Overpass/issues/33).
>
>If the font includes tall/deep writing systems such as Arabic or Devanagari, the winAscent and winDescent can be greater than the yMax and abs(yMin) to accommodate vowel marks.
>
>When the win Metrics are significantly greater than the upm, the linespacing can appear too loose. To counteract this, enabling the OS/2 fsSelection bit 7 (Use_Typo_Metrics), will force Windows to use the OS/2 typo values instead. This means the font developer can control the linespacing with the typo values, whilst avoiding clipping by setting the win values to values greater than the yMax and abs(yMin).
>
* 🔥 **FAIL** OS/2.usWinDescent value should be equal or greater than 202, but got 128 instead. [code: descent]
</div></details>

@jenskutilek We acknowledge the project's design goals. However, our policy on vertical metrics prioritizes optimal performance in different usage scenarios, while also allowing for the possibility of future upgrades such as expanded language support, without causing any regressions.

In case some users would like to use the font with a narrower line height for the overlay effect, they can easily adjust it through the layout settings. This would avoid compromising the font's performance or further development by attaching it to fixed vertical metric values that cannot be altered in future updates.

**Comment by jenskutilek** [comment] 2023-08-05 19:29
I've tweaked the metrics so the built-in line height is 120% of the em.

First I tried to keep the Typo Metrics at 100% (= 8 pixel height), but that lead to fontbakery complaining that the hhea ascender needs to match the typo ascender. Setting the hhea ascender to the typo ascender (896) in turn generated another complaint, that the sum of hhea ascender and descender was too small.

I guess it is fine now with all metrics identical, but if you have a better idea to preserve the original tight linespacing ...

**Comment by vv-monsalve** [comment] 2023-08-12 01:16
> I guess it is fine now with all metrics identical, but if you have a better idea to preserve the original tight linespacing ...

I'm afraid that is not possible given our spec, for the above (previous comment) reasons. I will review the latest files in the repository and provide further feedback.

**Comment by vv-monsalve** [comment] 2023-08-18 00:18
Hi Jens, I have adjusted the vertical metrics to follow the spec better. However, before creating a PR, we'll go over the two open issues with Dave to have a confirmation before proceeding. I will update this issue when we have an answer.

**Comment by vv-monsalve** [comment] 2023-08-18 22:04
Comparison between original vertical metric values and new ones following our spec.


![VM-old-new-comparison](https://github.com/jenskutilek/homecomputer-fonts/assets/48698976/7a4badc8-e054-4699-bb47-671291a25560)

**Comment by vv-monsalve** [comment] 2023-08-22 21:34
@jenskutilek, after resolving the issue with @davelab6 and considering the font's historical concept, we've decided to publish it with the following criteria: 
- The vertical metrics will comply with our vertical metrics to ensure no clipping, and the use of Typo Metrics is allowed. But the line-height values can remain original to produce the intended overlap effect. 
- The fonts will not support additional languages and that should be clearly stated in the Description file. 

Please restore the original desired vertical metrics values so we can perform the next QA round and proceed with the publishing process.

**Comment by jenskutilek** [comment] 2023-08-30 17:11
Thanks! I've tweaked the metrics again, so that the typo and hhea metrics will produce the desired tight/overlapping line height, and the winAscent/winDescent was kept as in the previous version to prevent clipping. @vv-monsalve can you check again if that's OK?

**Comment by vv-monsalve** [comment] 2023-09-05 02:00
Thank you, @jenskutilek. I've pulled the latest files and performed some production fixes included in the PR I opened now.

Regarding the VM, everything looks as expected. Please check the images below and confirm it is the case.


### Sixtyfour

![diffbrowsers_text-macOS-12 6 3-x86_64-i386-64bit_chrome_116 0 5845 140](https://github.com/jenskutilek/homecomputer-fonts/assets/48698976/7fa1e7bc-cc41-4118-be18-5354603b0450)

![diffbrowsers_text-macOS-12 6 3-x86_64-i386-64bit_firefox_116 0 2](https://github.com/jenskutilek/homecomputer-fonts/assets/48698976/d9a8b1ae-f3e4-446c-89be-ec4337bba0be)

**Comment by vv-monsalve** [comment] 2023-09-05 02:13
### Workbench

![diffbrowsers_text-macOS-12 6 3-x86_64-i386-64bit_firefox_116 0 2](https://github.com/jenskutilek/homecomputer-fonts/assets/48698976/a15db60f-d1af-4cf9-8ee5-fa14b0a55b80)
![diffbrowsers_text-macOS-12 6 3-x86_64-i386-64bit_firefox_116 0 2](https://github.com/jenskutilek/homecomputer-fonts/assets/48698976/cbd40678-24c6-497e-8b93-ce177d27770b)

**Comment by jenskutilek** [comment] 2023-09-06 07:18
Thanks @vv-monsalve, the images look as intended.

**Closed by jenskutilek** 2023-09-06 07:18 UTC
